### ISSUE TITLE
Questions about USB Audio

### ISSUE THREAD

**Issue by fyyxxm** [STMicroelectronics/stm32f4xx_hal_driver#12]
In the description of USB audio device unit, only mute control (0x01) is set, which can be recognized normally. However, setting mute control and volume control (0x01 | 0x02) will fail to recognize.

mcu: stm32f427.
IDE: keil.
using STMCubeMX 6.5 and STM32F4 lib 1.27

![001](https://user-images.githubusercontent.com/50574073/162239832-a2eb470f-2f7c-4c9d-887f-3f973f47a688.png)

**Comment by ALABSTM** [comment]
Hi @fyyxxm,

Any update from your side. Could you overcome this issue you described here? Otherwise, would it be possible to update the above screenshot with English language instead of Chinese?

Thanks,

**Comment by fyyxxm** [comment]
The project has ended and there is currently no need to solve this problem. Thank you for your help
