### ISSUE TITLE
Potential design issue/unwanted behavior in/of HAL_SPI_Receive_DMA() #2

### ISSUE THREAD

**Issue by lebakassemmerl** [STMicroelectronics/stm32f4xx_hal_driver#26]
Since I have no permission to re-open a ticket, I just wanted to open another one and point to the old one: #24 . I'm sorry that I didn't answer for such a long time that the ticket got closed.

**Comment by TOUNSTM** [comment]
Hello @lebakassemmerl 

Thank you for your contribution, I will reopen the main issue and close this thread.

With regards,
