### ISSUE TITLE
Can I built up this lib for RPi Pico RP2040?

### ISSUE THREAD

**Issue by user-redans** [STMicroelectronics/stm32f4xx_hal_driver#30]
Hi,

I've connected to my Pico via SPI1 an STEVAL-MKI208V1K board with an IIS3DWB vibration sensor and I want to read data from it.
I want to compile this driver for RPi Pico RP2040, can I do that?

**Comment by ALABSTM** [comment]
Hi @user-redans,

Thank you for your question. However, as indicated in the [CONTRIBUTING.md](https://github.com/STMicroelectronics/stm32f4xx_hal_driver/blob/v1.8.3/CONTRIBUTING.md#1-before-opening-an-issue), such support requests should be rather summitted to the [ST Community](https://community.st.com/t5/stm32-mcus-products/bd-p/stm32-mcu-products-forum). There you will hopefully find the answers you are looking for.

Please allow me to close this thread. Thank you for your comprehension.

With regards,
