### ISSUE TITLE
Wrong cast in stm32f4xx_ll_adc.h

### ISSUE THREAD

**Issue by leodicarpaccio** [STMicroelectronics/stm32f4xx_hal_driver#8]
Tag : v1.7.13
File concerned : stm32f4xx_ll_adc.h
Lines concerned : L4019 and L4034

Details : 
Both APIs, LL_ADC_REG_ReadConversionData8 and LL_ADC_REG_ReadConversionData6, return a unsigned char (uint8_t) while the value returned is cast in a uint16_t.
It cause a compilation error/warning. It should be corrected.

**Comment by RKOUSTM** [comment]
Hi @leodicarpaccio,

Thank you for this report. Your point is correct. It will be logged into our internal database and a fix will be made available in the frame of a future release.

Thank you once again for your report.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 118485
