### ISSUE TITLE
Unused variable tickstart in HAL_QSPI_Command_IT in stm32f4xx_hal_qspi.c makes gcc unhappy

### ISSUE THREAD

**Issue by sgauche** [STMicroelectronics/stm32f4xx_hal_driver#9]
**Caution**

The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post your report to the **ST Community** in the STM32 MCUs dedicated [page](https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus).

**Describe the set-up**

 * Custom Board with STM32F412CG
 * gcc-arm-none-eabi-10-2020-q4-major

**Describe the bug (skip if none)**

Unused variable `tickstart` makes gcc unhappy
https://github.com/STMicroelectronics/stm32f4xx_hal_driver/blob/master/Src/stm32f4xx_hal_qspi.c#L873

```
st_driver/stm32f4xx_hal_driver/Src/stm32f4xx_hal_qspi.c: In function 'HAL_QSPI_Command_IT':
st_driver/stm32f4xx_hal_driver/Src/stm32f4xx_hal_qspi.c:873:12: error: unused variable 'tickstart' [-Werror=unused-variable]
  873 |   uint32_t tickstart = HAL_GetTick();
      |            ^~~~~~~~~
cc1: all warnings being treated as errors
```

**How to reproduce the bug (skip if none)**

**Additional context**

**Screenshots**

**Comment by ASELSTM** [comment]
Hi @sgauche,

This issue has been fixed in the frame of version v1.8.0 of the  stm32g4xx_hal_driver published recently. Please allow me then to close this thread.

With regards,
